# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armazem',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
