# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armazem',
            options={'ordering': ['-atualizado', '-criado']},
        ),
        migrations.AddField(
            model_name='armazem',
            name='complemento',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='armazem',
            name='endereco',
            field=models.CharField(max_length=40),
        ),
    ]
