# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armazem',
            name='localizador',
        ),
    ]
