# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0002_auto_20160705_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armazem',
            options={'ordering': ['-atualizado', '-criado'], 'permissions': (('pode_administrar', 'Pode Administrar'),)},
        ),
    ]
