# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0003_auto_20160706_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazem',
            name='numero',
            field=models.CharField(max_length=6),
        ),
    ]
