# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0004_auto_20160711_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
