# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armazem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('estoque', models.IntegerField()),
                ('estoque_minimo', models.IntegerField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='armazem.Armazem')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedor.Fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado', '-criado'],
                'permissions': (('pode_administrar', 'Pode Administrar'),),
            },
        ),
    ]
