# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-atualizado', '-criado'], 'permissions': (('pode_administrar', 'Pode Administrar'),)},
        ),
    ]
