# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0004_auto_20160711_1442'),
        ('item', '0003_auto_20160706_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='armazem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armazem.Armazem'),
            preserve_default=False,
        ),
    ]
