# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0011_fornecedor_bairro'),
        ('item', '0004_item_armazem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.Fornecedor'),
            preserve_default=False,
        ),
    ]
