# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estoque_minimo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
