# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_estoque_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedor.Fornecedor'),
        ),
    ]
