# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20160811_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='armazem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='armazem.Armazem'),
        ),
    ]
