# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['sigla'], 'permissions': (('pode_adicionar', 'Pode Adicionar'),)},
        ),
    ]
