# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='numero',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
