# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0002_requisicao_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='numero',
        ),
    ]
