# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0004_requisicaoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicaoitem',
            old_name='atendido',
            new_name='situacao',
        ),
    ]
