# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0005_auto_20160927_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='situacao',
            field=models.BooleanField(default=False),
        ),
    ]
