# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaosocial', models.CharField(max_length=80)),
                ('nomefantasia', models.CharField(max_length=40)),
                ('cnpj', models.CharField(max_length=14)),
                ('atividade', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=6)),
                ('complemento', models.CharField(max_length=40, null=True)),
                ('cep', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('situacao', models.BooleanField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Municipio')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado', '-criado'],
                'permissions': (('pode_administrar', 'Pode Administrar'),),
            },
        ),
    ]
