# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
