# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_auto_20160608_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
