# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0003_fornecedor_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='situacao',
            field=models.BooleanField(),
        ),
    ]
