# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0004_auto_20160608_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado'),
        ),
    ]
