# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fornecedor', '0006_auto_20160609_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
