# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0007_fornecedor_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['-atualizado', '-criado'], 'permissions': (('pode_administrar', 'Pode Administrar'),)},
        ),
    ]
