# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0008_auto_20160706_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
