# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0010_auto_20160711_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='bairro',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
