# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0012_auto_20160811_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
