# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0013_fornecedor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
