# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 16:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('fornecedor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('data_compra', models.DateField(default=datetime.datetime.today)),
                ('data_entrega', models.DateField(default=datetime.datetime.today)),
                ('situacao', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-atualizado', '-criado'],
                'permissions': (('pode_administrar', 'Pode Administrar'),),
            },
        ),
        migrations.CreateModel(
            name='Itemcompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedor.Fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Item')),
            ],
            options={
                'ordering': ['item'],
                'permissions': (('pode_administrar', 'Pode Administrar'),),
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='itens',
            field=models.ManyToManyField(to='compra.Itemcompra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
