# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 10, 40, 59, 374834)),
        ),
    ]
