# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='estoque',
            new_name='situacao',
        ),
    ]
