# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_compra_fornecedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='nota',
            new_name='notafiscal',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fornecedor',
        ),
    ]
