# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('compra', '0005_auto_20160822_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.Item')),
            ],
            options={
                'ordering': ['item'],
                'permissions': (('pode_administrar', 'Pode Administrar'),),
            },
        ),
        migrations.AlterField(
            model_name='compra',
            name='itens',
            field=models.ManyToManyField(to='compra.CompraItem'),
        ),
    ]
