# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_auto_20160822_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
