# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_compraitem_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='itens',
        ),
        migrations.AddField(
            model_name='compra',
            name='itens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='compra.CompraItem'),
            preserve_default=False,
        ),
    ]
