# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0008_auto_20160824_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='itens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.CompraItem'),
        ),
    ]
