# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0009_auto_20160824_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='itens',
        ),
        migrations.AlterField(
            model_name='compra',
            name='notafiscal',
            field=models.CharField(max_length=20),
        ),
    ]
