# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('compra', '0010_auto_20160829_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fornecedor.Fornecedor'),
            preserve_default=False,
        ),
    ]
