# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0012_auto_20160830_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
