# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0015_compra_complemento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='complemento',
            new_name='observacao',
        ),
    ]
