# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armazem', '0001_initial'),
        ('compra', '0020_remove_compra_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompra',
            name='armazem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='armazem.Armazem'),
            preserve_default=False,
        ),
    ]
