# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0021_itemcompra_armazem'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
