# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0022_compra_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(),
        ),
    ]
