# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0023_auto_20160921_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 20, 17, 41, 19, 157379)),
        ),
    ]
