# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0024_auto_20160921_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 21, 7, 5, 45, 827034)),
        ),
    ]
