# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0026_auto_20160922_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcompra',
            old_name='usuario',
            new_name='requisitante',
        ),
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 21, 14, 47, 28, 403066)),
        ),
    ]
