# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0027_auto_20160922_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 21, 17, 58, 7, 454171)),
        ),
    ]
