# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0028_auto_20160922_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 22, 12, 37, 33, 395777)),
        ),
    ]
