# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0029_auto_20160923_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 22, 12, 41, 43, 421077)),
        ),
    ]
