# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0033_auto_20160923_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 22, 14, 27, 5, 180661)),
        ),
    ]
