# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0035_auto_20160923_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 22, 18, 13, 0, 256345)),
        ),
    ]
