# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0036_auto_20160923_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 25, 7, 35, 32, 996398)),
        ),
    ]
