# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0038_auto_20160926_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 26, 8, 15, 15, 612275)),
        ),
    ]
