# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0039_auto_20160927_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data_pagamento',
            field=models.DateField(default=datetime.datetime(2016, 12, 26, 14, 7, 42, 684024)),
        ),
    ]
